/* eslint-disable @next/next/link-passhref */

import { NextPage } from "next";
import Head from "next/head";
import { Heading, Center, Input, Box, VStack, Button } from "@chakra-ui/react";
import styles from "../styles/Home.module.css";

//@ts-ignore
import ReCAPTCHA from "react-google-recaptcha";
function onChange(value: any) {
  console.log("Captcha value:", value);
}

const Faucet: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sapiens News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.values}>
        <Center h="100vh">
          <VStack>
            <Box color="white">
              <Heading>Faucet</Heading>
            </Box>
            <Box width="40vw">
              <Input color="white"></Input>
            </Box>
            <Box>
              <input id="yourFirstCaptchaUserInput" type="text" />
              <ReCAPTCHA sitekey="Your client site key" onChange={onChange} />
              <Button>Request tokens</Button>
            </Box>
          </VStack>
        </Center>
      </main>
      <div></div>
    </div>
  );
};

export default Faucet;
