/* eslint-disable @next/next/link-passhref */

import { NextPage } from "next";
import Head from "next/head";
import { Heading, Center, Input, Box, VStack, Button } from "@chakra-ui/react";
import styles from "../styles/Home.module.css";

//@ts-ignore
import ReCAPTCHA from "react-google-recaptcha";

import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
} from "@chakra-ui/react";
import { useState } from "react";

const Faucet: NextPage = () => {
  const [isOpen, setIsOpen] = useState(false);

  function onChange(value: any) {
    closeModal();
    // sendtokens
  }

  const openModal = () => {
    setIsOpen(true);
  };

  const closeModal = () => {
    setIsOpen(false);
  };

  return (
    <div>
      <Modal isCentered isOpen={isOpen} onClose={closeModal}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Modal Title</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <input id="yourFirstCaptchaUserInput" type="text" />
            <ReCAPTCHA
              sitekey={"6LcRIuMeAAAAAC2NfG-vwoRVtlZT-IzySN7yPc2z"}
              onChange={onChange}
            />
          </ModalBody>
          <ModalFooter></ModalFooter>
        </ModalContent>
      </Modal>
      <Head>
        <title>Sapiens News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.values}>
        <Center h="100vh">
          <VStack>
            <Box color="white">
              <Heading>Faucet</Heading>
            </Box>
            <Box width="40vw">
              <Input color="white"></Input>
            </Box>
            <Box>
              <Button onClick={openModal}>Request tokens</Button>
            </Box>
          </VStack>
        </Center>
      </main>
      <div></div>
    </div>
  );
};

export default Faucet;
